### ISSUE TITLE
length=${#FUNCNAME/#cfg_section_;[*]}: bad substitution

### ISSUE THREAD

**Issue by gesinn-it** [albfan/bash-ini-parser#9] opened 2016-08-30 12:36 UTC
`bash-ini-parser: line 98: length=${#FUNCNAME/#cfg_section_;[*]}: bad substitution`

happens when trying to

```
cfg_update webserver ws_document_root
cfg_writer > manage.ini
```

My manage.ini file looks as follows:

```
[webserver]
ws_document_root="/var/www"
```

bash version: GNU bash, version 4.2.47(1)-release (x86_64-suse-linux-gnu)

Even removing the "/" and setting a simple string like "var", fails with the same error. Any idea?

**Comment by gesinn-it** [comment] 2016-08-30 13:52
Steps to reproduce:

_manage.ini_
```
[webserver]
wsdocumentroot="www"
```

_test.sh_
```
#!/bin/bash
source bash-ini-parser
cfg_parser "manage.ini"
cfg_section_webserver
cfg_writer
cfg_update webserver wsdocumentroot
cfg_writer
#cfg_writer > manage.ini
```

This leads to:
```
vagrant-sles-12-x64:/vagrant/vagrant_share/2016.11.0 # bash test.sh
[webserver]
wsdocumentroot="www"
[webserver]
bash-ini-parser: line 100: length=${#FUNCNAME/#cfg_section_;[*]}: bad substitution
bash-ini-parser: line 101: [: ==: unary operator expected
;FUNCNAME/#cfg_section_; is an array
FUNCNAME/#cfg_section_;="cfg_writer"
wsdocumentroot="www"
wsdocumentroot="www"
wsdocumentroot="www"
```

**Comment by albfan** [comment] 2016-08-31 05:34
Great to provide a SCCE. Are you brave enough to provide a failed test?

I will check that and see if I can reproduce it.

**Comment by gesinn-it** [comment] 2016-08-31 06:40
Thanks for having a look into this.

Not sure if I can provide a test case. I was working with _bash-ini-parser_ only (without the other files).

But it should be easy to reproduce if you follow my second comment. It looks like _cfg_update_ is messing up something.

**Comment by gesinn-it** [comment] 2016-09-09 12:50
Hi Alberto, did you have a chance to reproduce the issue?

**Comment by pavreh** [comment] 2018-05-22 21:18
Hallo, I have the same experience when I follow Updating and saving changes from readme.md. There is a solution.

**Comment by albfan** [comment] 2018-05-23 00:30
@pavreh, can you add a test case for this n PR?

**Comment by pavreh** [comment] 2018-05-23 16:17
Sure.
file.ini
**content of file.ini:**
[section]
   key = value
   key2 = value2

**execute:**
$ . bash-ini-parser
$ cfg_parser file.ini
$ cfg_section_section
$ echo $key
value
$ echo $key2
value2
$ var=new_value
$ cfg_update section var
$ cfg_writer > newfile.ini
bash: length=${#FUNCNAME/#cfg_section_;[*]}: bad substitution
bash: [: ==: unary operator expected

**content of the newfile.ini:**
[section]
;FUNCNAME/#cfg_section_; is an array
FUNCNAME/#cfg_section_;="cfg_writer"
key="value"
key="value"
key2="value2"
var="var"

As you can see there is even more issues. newfile.ini is corrupted by a two lines (PR #16 resolve it), key="value" is duplicated (I have a solution so I will commit a new PR for this), var is "var" but it should be "new_value" (name of a variable must not be var since key3=new_value works fine).

Pavel

**Comment by albfan** [comment] 2018-05-23 17:09
I mean code it like:

https://github.com/albfan/bash-ini-parser/blob/master/t/t0004-comments.sh

@pavel, new problem, new issues, ok?

**Comment by albfan** [comment] 2018-05-25 05:19
@gesinn-it Check if master fixes this for you, if so close this issue

@pavreh: thanks for working on this

**Closed** 2018-05-27 11:26 UTC
