### ISSUE TITLE
cfg_parser error

### ISSUE THREAD

**Issue by lsafelix75** [albfan/bash-ini-parser#38] opened 2020-12-13 15:47 UTC
The following section crashes the script with error:

```
_syntax error near unexpected token `"ab:ab:ab:ab:ee:ee"'
`CCTV1/UID=( "ab:ab:ab:ab:ee:ee" )'_
```

Source file:
```
[CCTV]
CCTV1/UID="ab:ab:ab:ab:ee:ee"
CCTV1/USERNAME=user
CCTV1/PASSWORD=abc
CCTV1/IMAGE_LOCATION="/usr/lib/"
```

**Comment by milanbalazs** [comment] 2021-01-06 11:26
What is your expectation? The problem is the invalid key names. The `/` character is not allowed in the keys.
If you try to use  the `CCTV1/UID` variable name in bash simply, you will also get error due to the `/` character is not allowed in the variable names in Bash.

```
>>> CCTV1/UID=test
bash: CCTV1/UID=test: No such file or directory
```

It means the Bash INI parser is also not able to convert this key to Bash variable.
A possible solution to remove the `CCTV1/` prefix from your keys.

**Correct INI file format:**
```
[CCTV]
# UID="ab:ab:ab:ab:ee:ee"
USERNAME=user
CCTPASSWORD=abc
IMAGE_LOCATION="/usr/lib/"
```

**Example code:**
```
source scripts/bash_ini_parser.sh

cfg_parser test.ini
cfg_section_CCTV
echo "USERNAME: ${USERNAME}"
echo "CCTPASSWORD: ${CCTPASSWORD}"
echo "IMAGE_LOCATION: ${IMAGE_LOCATION}"
```

**Output:**
```
>>> ./test.sh 
USERNAME: user
CCTPASSWORD: abc
IMAGE_LOCATION: /usr/lib/
```

**NOTE:**
I have commented out the `UID` option from the INI file due to it is a readonly variable on Linux machines so it cannot be unset:
```
scripts/bash_ini_parser.sh: line 151: unset: UID: cannot unset: readonly variable
scripts/bash_ini_parser.sh: line 64: UID: readonly variable
```

**I am recommending to close this ticket because it is not related to Bash INI parser implementations.**

**Comment by albfan** [comment] 2021-01-06 14:00
Thanks a lot @milanbalazs

@lsafelix75 sadly, this tiny implementation relies on bash defaults, so you should design your ini file to deal with bash.

If the ini format is imposed from other system your out of luck here. If you can change the format I subscribe all the Milan suggestions.

We can reopen the issue if format is mandatory, but that will imply hacky options to circumvent bash limitations, without warranties to find a satisfactory solution.  Time ago I think about using section to prefix variables, and this seems to be a solution for one of your problems. The other will need more thinking (preventive replace for invalid variable characters or similar, not sure)

**Closed as completed by albfan** 2021-01-06 14:00 UTC
